export const WORDS = [
  'apple', 'beach', 'brain', 'bread', 'brush',
  'chair', 'chest', 'chord', 'click', 'clock',
  'cloud', 'dance', 'diary', 'drink', 'drive',
  'earth', 'feast', 'field', 'fruit', 'glass',
  'grape', 'green', 'ghost', 'guide', 'heart',
  'horse', 'house', 'juice', 'light', 'lemon',
  'melon', 'money', 'music', 'night', 'party',
  'piano', 'pilot', 'plane', 'plant', 'plate',
  'phone', 'power', 'radio', 'river', 'robot',
  'shirt', 'shoes', 'space', 'spoon', 'stage',
  'stair', 'store', 'storm', 'story', 'sugar',
  'table', 'taste', 'tiger', 'toast', 'tower',
  'track', 'trade', 'train', 'truck', 'uncle',
  'video', 'voice', 'waste', 'watch', 'water',
  'whale', 'white', 'woman', 'world', 'write',
  'youth', 'zebra', 'abuse', 'adult', 'agent',
  'anger', 'award', 'basis', 'beach', 'birth',
  'block', 'blood', 'board', 'brain', 'bread',
  'break', 'brown', 'buyer', 'cause', 'chain',
  'chair', 'chest', 'chief', 'child', 'china',
  'claim', 'class', 'clock', 'coach', 'coast',
  'court', 'cover', 'cream', 'crime', 'cross',
  'crowd', 'crown', 'cycle', 'dance', 'death',
  'depth', 'doubt', 'draft', 'drama', 'dream',
  'dress', 'drive', 'earth', 'enemy', 'entry',
  'error', 'event', 'faith', 'fault', 'field',
  'fight', 'final', 'floor', 'focus', 'force',
  'frame', 'frank', 'front', 'fruit', 'glass',
  'grant', 'grass', 'green', 'group', 'guide',
  'heart', 'henry', 'horse', 'hotel', 'house',
  'image', 'index', 'input', 'issue', 'japan',
  'jones', 'judge', 'knife', 'laura', 'layer',
  'level', 'lewis', 'light', 'limit', 'lunch',
  'major', 'march', 'match', 'metal', 'model',
  'money', 'month', 'motor', 'mouth', 'music',
  'night', 'noise', 'north', 'novel', 'nurse',
  'offer', 'order', 'other', 'owner', 'panel',
  'paper', 'party', 'peace', 'peter', 'phase',
  'phone', 'piece', 'pilot', 'pitch', 'place',
  'plane', 'plant', 'plate', 'point', 'pound',
  'power', 'press', 'price', 'pride', 'prize',
  'proof', 'queen', 'radio', 'range', 'ratio',
  'reply', 'right', 'river', 'round', 'route',
  'rugby', 'scale', 'scene', 'scope', 'score',
  'sense', 'shape', 'share', 'sheep', 'sheet',
  'shift', 'shirt', 'shock', 'sight', 'simon',
  'skill', 'sleep', 'smile', 'smith', 'smoke',
  'sound', 'south', 'space', 'speed', 'spite',
  'sport', 'squad', 'staff', 'stage', 'start',
  'state', 'steam', 'steel', 'stock', 'stone',
  'store', 'study', 'stuff', 'style', 'sugar',
  'table', 'taste', 'terry', 'theme', 'thing',
  'title', 'total', 'touch', 'tower', 'track',
  'trade', 'train', 'trend', 'trial', 'trust',
  'truth', 'uncle', 'union', 'unity', 'value',
  'video', 'visit', 'voice', 'waste', 'watch',
  'water', 'while', 'white', 'whole', 'woman',
  'world', 'worry', 'write', 'youth'
]

export const getRandomWord = () => {
  return WORDS[Math.floor(Math.random() * WORDS.length)]
}
